---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install base packages
  ansible.builtin.apt:
    name: "{{ base_packages }}"
    state: present

- name: Create application directory
  ansible.builtin.file:
    path: "{{ app_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create application log directory
  ansible.builtin.file:
    path: "{{ app_log_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
