input {
  beats {
    port => 5044
  }
}

filter {
  if [app][level] {
    mutate {
      add_field => { "log_level" => "%{[app][level]}" }
    }
  }
  if [app][msg] {
    mutate {
      add_field => { "log_message" => "%{[app][msg]}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "app-logs-%{+YYYY.MM.dd}"
  }
}
